name: "Close issues"

on:
  issues:
    types: ["opened"]

jobs:
  close-issue:
    permissions:
      issues: "write"
    name: "Close issue"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/github-script@v7"
        with:
          script: |
            const issues_url = context.serverUrl + '/' + context.repo.owner + '/' + context.repo.repo + '/issues/new/choose';
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Issues opened on this repository are not processed. Please follow links proposed in ${issues_url}.`
            });
            await github.rest.issues.lock({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            await github.rest.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "closed",
            });
